### ISSUE TITLE
Error: SubRegion Doesn't have a child

### ISSUE THREAD

**Issue by philippechehade** [GEOS-DEV/GEOS#2264]
when trying to initialize a simulation with a well, the below error appeared: 
![image](https://user-images.githubusercontent.com/119044257/216121492-ee30c1d0-9b94-42ac-83ff-46d90875afbc.png)

Can you provide us with an explanation about these subregions? I am having difficulties understanding how to define the well and what is this subregion supposed to mean ? 

@jeannepellerin

**Comment by francoishamon** [comment]
Thanks @philippechehade for reporting the problem. In fact, given your error message, the issue is in the `Tasks` block of the xml (specifically, in the `PackCollection` block) where the path to the value that you are trying to collection is probably invalid. I will check directly with you to get the input file and try to add a better error message.

**Comment by herve-gross** [comment]
@francoishamon is on it, and we will look at the error message.

**Comment by untereiner** [comment]
relies on #2404

**Comment by untereiner** [comment]
@philippechehade @francoishamon  Is this issue still relevant ?
