### ISSUE TITLE
Reduce compilation time on Travis.

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#2339]
Compilation times of CUDA builds on travis have reached the 3 hours limit again. Several PRs  cannot finish the travis jobs and thus cannot be merged.  

For example, the following PRs struggle with finishing cuda builds withing the time limits:
- https://github.com/GEOSX/GEOSX/pull/2064
- https://github.com/GEOSX/GEOSX/pull/2196

Proposed solution:
Define a mechanism to selectively compile combinations of constitutive models and finite element spaces so that, on the CI, only certain combinations are compiled with cuda.

**Comment by herve-gross** [comment]
@rrsettgast have you reached out to Travis on this?

**Comment by rrsettgast** [comment]
They have not responded to any of my inquiries. I think we should move everything to GitHub actions if possible

**Comment by TotoGaz** [comment]
Looks like we now can now have [larger runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#machine-specs-for-larger-runners). Is that new?
According to the [billing](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates) one build would cost us ~$16.

**Comment by TotoGaz** [comment]
It's surely possible to start with a few builds only?
That way we could test at small scalebefore engaging more funds (or even not duplicating the payments between `travis` and `github actions`).

**Comment by bmhan12** [comment]
I have a test PR here with Github Actions running the CUDA jobs:

PR: https://github.com/GEOS-DEV/GEOS/pull/2400

Github Actions run: https://github.com/GEOS-DEV/GEOS/actions/runs/4734316409

It looks to be working for the CUDA jobs, at least it is not running out of memory like Azure Pipelines was (we did move to ninja since then, maybe that is helping?). Longest runtime is 3h36 minutes, however (max time limit is 6 hours).


I have not adapted the jobs with google cloud deployment yet, because they need security keys (requires higher Github permissions). The cloud jobs do not hit the time limit on Travis, so I believe (naively) they should be fine on Github Actions.

**Comment by untereiner** [comment]
Does the PR #2400 do the job ? Can this issue be closed ?

**Comment by TotoGaz** [comment]
@bmhan12 I think this issue can be closed?
