### ISSUE TITLE
Adding check and warning message for defaultThermalExpansionCoefficient

### ISSUE THREAD

**Issue by jhuang2601** [GEOS-DEV/GEOS#2407]
**What is the requested feature?**
Currently, `defaultThermalExpansionCoefficient` needs to be defined separately in both the solid model and the `BiotPorosity` model for THM simulations. Different formulas might be used in different sections within the same xml file by end users. Sanity check is missing to protect GEOS from inconsistent or incomplete input.

**Is your request related to a specific problem?**
For this [tutorial example](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.html), if `defaultThermalExpansionCoefficient` is missing in the `BiotPorosity` model, simulation results deviate away from the corresponding analytical solution.
![image](https://user-images.githubusercontent.com/53012159/234130035-68f40885-a4c2-40f4-ad87-73ed2effcb7d.png)

**Describe the solution you'd like**
Sanity check and warning message are expected for `defaultThermalExpansionCoefficient` and related theory of `BiotPorosity` model should also be updated.

**Comment by sytuannguyen** [comment]
Indeed, they are two different coefficients both are required for simulating a THM coupling problem. Precisely, the `defaultThermalExpansionCoefficient` in the solid model is the drained linear TEC that related temperature change with strain in a drained free stress test while the one in BiotPorosity is another one for computing porosity variation due to temperature change in a drained free stress test. 

I would propose to change their name and description a little bit to clarify that they are not the same thing. There is also another one in `ThermalCompressibleSinglePhaseFluid` that is the thermal expansion coefficient of fluid. 

@francoishamon @jhuang2601 How do you think about rename them as: `defaultDrainedThermalExpansionCoefficient` in the solid model, `defaultPosorityThermalExpansionCoefficient` in the BiotPorosity model, `defaultFluidThermalExpansionCoefficient` in the fluid model.

**Comment by jhuang2601** [comment]
> Indeed, they are two different coefficients both are required for simulating a THM coupling problem. Precisely, the `defaultThermalExpansionCoefficient` in the solid model is the drained linear TEC that related temperature change with strain in a drained free stress test while the one in BiotPorosity is another one for computing porosity variation due to temperature change in a drained free stress test.
> 
> I would propose to change their name and description a little bit to clarify that they are not the same thing. There is also another one in `ThermalCompressibleSinglePhaseFluid` that is the thermal expansion coefficient of fluid.
> 
> @francoishamon @jhuang2601 How do you think about rename them as: `defaultDrainedThermalExpansionCoefficient` in the solid model, `defaultPosorityThermalExpansionCoefficient` in the BiotPorosity model, `defaultFluidThermalExpansionCoefficient` in the fluid model.

@sytuannguyen Concur with you on such necessary update.

**Comment by sytuannguyen** [comment]
> > Indeed, they are two different coefficients both are required for simulating a THM coupling problem. Precisely, the `defaultThermalExpansionCoefficient` in the solid model is the drained linear TEC that related temperature change with strain in a drained free stress test while the one in BiotPorosity is another one for computing porosity variation due to temperature change in a drained free stress test.
> > I would propose to change their name and description a little bit to clarify that they are not the same thing. There is also another one in `ThermalCompressibleSinglePhaseFluid` that is the thermal expansion coefficient of fluid.
> > @francoishamon @jhuang2601 How do you think about rename them as: `defaultDrainedThermalExpansionCoefficient` in the solid model, `defaultPosorityThermalExpansionCoefficient` in the BiotPorosity model, `defaultFluidThermalExpansionCoefficient` in the fluid model.
> 
> @sytuannguyen Concur with you on such necessary update.

@francoishamon How do you think about this change?
