### ISSUE TITLE
Potential bug with ParallelTopologyChangeNoFixup

### ISSUE THREAD

**Issue by liyangrock** [GEOS-DEV/GEOS#3484]
**Describe the bug**
Asymmetric fracture propagation observed in hydraulic fracturing simulations when using the new ParallelTopologyChangeNoFixup. This behavior emerged after the surface generator was updated to use the new version of ParallelTopologyChange. The issue is reproducible in the latest develop branch but does not exist in previous versions. Reverting to the old implementation by setting `PARALLEL_TOPOLOGY_CHANGE_METHOD=0` in `ParallelTopologyChange.hpp` resolves the issue, indicating a potential bug in the new implementation of `ParallelTopologyChange` or something in `hydrofractureSolver` is incompatible with the new `ParallelTopologyChange`.

**To Reproduce**
1. Use the attached simulation file with two configurations:
   - New version: ParallelTopologyChangeNoFixup.cpp (`PARALLEL_TOPOLOGY_CHANGE_METHOD=1`)
   - Old version: ParallelTopologyChange.cpp (`PARALLEL_TOPOLOGY_CHANGE_METHOD=0`)

[fracture.xml.txt](https://github.com/user-attachments/files/18046072/fracture.xml.txt)

**Screenshots**
New implementation (ParallelTopologyChangeNoFixup.cpp):
![1-1](https://github.com/user-attachments/assets/7bd77d3b-b660-4b62-a857-42568f35aa56)

Original implementation (ParallelTopologyChange.cpp):
![1-2](https://github.com/user-attachments/assets/8aefd4f3-7fa8-4a38-be0c-cc3d80708e49)

**Platform (please complete the following information):**
- Machine: Ubuntu 22.04
- Compiler: gcc 11.4.0
- GEOS Version: latest develop

**Additional context**
The issue appears to be specific to hydraulic fracturing in porous media simulations. Fracture propagation in solid media simulations remains unaffected.

**Comment by rrsettgast** [comment]
@liyangrock how many partitions in each direction?

**Comment by liyangrock** [comment]
> @liyangrock how many partitions in each direction?

Just 1 partition

**Comment by rrsettgast** [comment]
Hello @liyangrock 
I ran this input on develop. I have not been able to reproduce the issue you observe. Here is what I see in visit using silo outputs:

![Screenshot 2024-12-07 at 1 22 28 AM](https://github.com/user-attachments/assets/327a14a9-6497-40c6-b3f0-2c1450adf4cb)

I do notice some other concerning behavior at the fracture tip as the open faces on the tip are collapsed. 

if I make my scale really small and zoom in on the area you are seeing artifacts:
![Screenshot 2024-12-07 at 1 24 17 AM](https://github.com/user-attachments/assets/3a71ed09-a144-443b-9ef5-057cb7772c4a)


and finally if I plot the displacement vectors:
![Screenshot 2024-12-07 at 1 26 02 AM](https://github.com/user-attachments/assets/b6796a38-3fec-4af4-973d-f31f06158cdf)

So I don't see anything like the artifacts you observe. Can you rerun and verify that you didn't somehow see a paraview artifact?

also...if this is a single partition, the `ParallelToplogyChange` routines should be `no-op`...i.e. they do nothing because there is nothing to do...however this doesn't exclude the possibility that they are doing something that they are not supposed to do.

**Comment by liyangrock** [comment]
I appreciate your help @rrsettgast . I will double-check the things you mentioned on my side.

**Comment by liyangrock** [comment]
Sorry @rrsettgast I've traced the issue back to my modifications in `SurfaceGenerator.cpp` where I introduced the `axom` library. Here's what I found:

1. Original SurfaceGenerator works correctly, matching your results
2. Modified SurfaceGenerator shows different behavior:
     - Works fine with old ParallelTopologyChange
     - Shows issues with new ParallelTopologyChange
     - Interestingly, increasing `rockToughness` from `1e4` to `1e6` resolves the propagation issue

Since this appears to stem from my local modifications rather than the core code, I suggest closing this issue. Thank you for your help in tracking this down.

**Comment by rrsettgast** [comment]
@liyangrock what were the changes you made? What were you using axom to do?

**Comment by liyangrock** [comment]
> @liyangrock what were the changes you made? What were you using axom to do?

The current node splitting implementation seems have limitations with C3D4 elements for complex fracture splitting due to its simplified element location identification approach. I've implemented a solution that uses graph theory to identify closed separation planes. In this process, I use some functions from axom. The current Axom dependency is non-essential and was incorporated solely for convenience.

**Comment by liyangrock** [comment]
Hi @rrsettgast, I'm unsure if this is a bug. After switching to `ParallelTopologyChangeNoFixup`, it seems that the first member of `elemLocations` (i.e. `elemLocations[0]`) for a splitting node must be 0. Changing the following value from 0 to 1 causes a problem like the first figure of this issue (develop branch run without MPI partitions). Is it mandatory for this value to be 0?

https://github.com/GEOS-DEV/GEOS/blob/b3592de6f9773e995728462ca53242d40221e244/src/coreComponents/physicsSolvers/surfaceGeneration/SurfaceGenerator.cpp#L1545
